var components = {
    login: function () { return import("./login/Login.vue"); },
    home: function () { return import("./Home.vue"); },
    index: function () { return import("./Index.vue"); },
    fundsRecord: function () { return import("./FundsRecord.vue"); },
    adminInfo: function () { return import("./AdminInfo.vue"); },
    dealProduct: function () { return import("./DealProduct.vue"); },
    orderError: function () { return import("./OrderError.vue"); },
    recharge: function () { return import("./Recharge.vue"); },
    withdraw: function () { return import("./Withdraw.vue"); },
    productFields: function () { return import("./ProductFields.vue"); },
    productTypes: function () { return import("./ProudctTypes.vue"); },
    productAll: function () { return import("./ProudctAll.vue"); },
    placardsPlatform: function () { return import("./PlacardsPlatform.vue"); },
    placardsSite: function () { return import("./PlacardsSite.vue"); },
    sites: function () { return import("./Sites.vue"); },
    users: function () { return import("./Users.vue"); },
    feedbackSite: function () { return import("./FeedbackSite.vue"); },
    feedbackUser: function () { return import("./FeedbackUser.vue"); },
    adminsRole: function () { return import("./AdminsRole.vue"); },
    adminsList: function () { return import("./AdminsList.vue"); },
    platformInfo: function () { return import("./PlatformInfo.vue"); },
    right: function () { return import("./Right.vue"); },
    siteRight: function () { return import("./SiteRight.vue"); },
    userRight: function () { return import("./UserRight.vue"); },
    documentEditor: function () { return import("./DocumentEditor.vue"); },
};
export default components;
//# sourceMappingURL=index.js.map