const components = {
    login: () => import("./login/Login.vue"),
    home: () => import("./Home.vue"),
    index: () => import("./Index.vue"),
    fundsRecord: () => import("./FundsRecord.vue"),
    adminInfo: () => import("./AdminInfo.vue"),
    dealProduct: () => import("./DealProduct.vue"),
    orderError: () => import("./OrderError.vue"),
    recharge: () => import("./Recharge.vue"),
    withdraw: () => import("./Withdraw.vue"),
    productFields: () => import("./ProductFields.vue"),
    productTypes: () => import("./ProudctTypes.vue"),
    productAll: () => import("./ProudctAll.vue"),
    placardsPlatform: () => import("./PlacardsPlatform.vue"),
    placardsSite: () => import("./PlacardsSite.vue"),
    sites: () => import("./Sites.vue"),
    users: () => import("./Users.vue"),
    feedbackSite: () => import("./FeedbackSite.vue"),
    feedbackUser: () => import("./FeedbackUser.vue"),
    adminsRole: () => import("./AdminsRole.vue"),
    adminsList: () => import("./AdminsList.vue"),
    platformInfo: () => import("./PlatformInfo.vue"),
    right: () => import("./Right.vue"),
    siteRight: () => import("./SiteRight.vue"),
    userRight: () => import("./UserRight.vue"),
    documentEditor: () => import("./DocumentEditor.vue"),
};

export default components;