var components = {
    noPage: function () { return import("@/components/NoPage.vue"); },
    login: function () { return import("./login/Login.vue"); },
    home: function () { return import("./Home.vue"); },
    index: function () { return import("./Index.vue"); },
    adminInfo: function () { return import("./AdminInfo.vue"); },
    dealProduct: function () { return import("./DealProduct.vue"); },
    recharge: function () { return import("./recharge/Recharge.vue"); },
    rechargeRecord: function () { return import("./RechargeRecord.vue"); },
    consumeRecord: function () { return import("./ConsumeRecord.vue"); },
    profitRecord: function () { return import("./ProfitRecord.vue"); },
    withdraw: function () { return import("./Withdraw.vue"); },
    withdrawRecord: function () { return import("./WithdrawRecord.vue"); },
    productType: function () { return import("./ProductType.vue"); },
    product: function () { return import("./Product.vue"); },
    adminRole: function () { return import("./AdminRole.vue"); },
    admins: function () { return import("./Admins.vue"); },
    usersRole: function () { return import("./UsersRole.vue"); },
    users: function () { return import("./Users.vue"); },
    placard: function () { return import("./Placard.vue"); },
    feedback: function () { return import("./Feedback.vue"); },
    userFeedback: function () { return import("./UserFeedback.vue"); },
    settings: function () { return import("./Settings.vue"); },
};
export default components;
//# sourceMappingURL=index.js.map